### ISSUE TITLE
Guidence on usage

### ISSUE THREAD

**Issue by vincentparrett** [yahehe/Nancy.Swagger#50]
Hi All

I was excited to find this project today, looking for a way to make my nancy http api self documenting. 

I have no clue how to use it? The only config I see in the example is a single static folder  convention that is mapping a folder that doesn't exist in the project? What am I missing?

**Comment by jnallard** [comment]
> I have no clue how to use it? The only config I see in the example is a single static folder convention that is mapping a folder that doesn't exist in the project? What am I missing?

I assume you're talking about the example. That static folder mapping is used to serve the swagger-ui files, which are copied from /lib/ during the example's build process. For your project, you can figure out how to serve the files yourself or you can just submit your URL into the text field at the top of http://petstore.swagger.io/ in order to view your API.

Other than that, I believe there's not much config required besides actually describing the routes, which you can see in the *MetadataModule classes. 
There is the ability to set the info, such as the name and contacts, for your API, which I added recently. This can be used via: `SwaggerMetadataProvider.SetInfo()`.

**Comment by yahehe** [comment]
@jnallard is working on wiki documentation
