### ISSUE TITLE
why Unable to get the webapi document for my project?

### ISSUE THREAD

**Issue by tiandao-dongguan** [yahehe/Nancy.Swagger#73]
in the example code ,Swagger url is :http://localhost:62831/docs/index.html,but Unable to get the webapi document for my project, i use swagger-ui V2. in index.html page,the url in address  show : http://petstore.swagger.io/v2/swagger.json, why?

**Comment by yahehe** [comment]
Hard to say without any code examples. Is your index.html pulling the swagger.json from /api-docs or /swagger.json ?

**Comment by jnallard** [comment]
If I recall, when you download the swagger-ui, it has the http://petstore.swagger.io/v2/swagger.json URL hardcoded into the index.js file. 
If you modify this line in your local copy: https://github.com/swagger-api/swagger-ui/blob/master/src/main/html/index.html#L41
to http://localhost:62831/swagger.json or http://localhost:62831/api-docs it should work.

In the example code, the /docs/index.html link should show you the swagger-ui page; so if you place the swagger-ui folder in Nancy.Swagger/lib, (so that the folder structure looks like [...]/Nancy.Swagger\lib\swagger-ui\dist), the example's build process will copy these documents so that it will be shown when you run the program.

**Comment by tiandao-dongguan** [comment]
@yahehe @jnallard oh,thank you very much~it,s ok .thank you
